add Audio API support for axis network speakers
Kane610/axis pull request #521
Opened 2024-11-11 03:32 UTC by jonoberheide

Ok, I stepped out of HA-land [1] for a bit to add the Audio API support natively to the axis library.

This PR:
- Adds the skeleton for the Audio API
- Adds the transmit.cgi request to send audio to the speaker
- Adds a ffmpeg helper to transcode any input audio to the right format
- Adds a --audio flag to be able to invoke it and play audio from the cmdline

[1] https://github.com/home-assistant/core/pull/130163

2024-11-11 11:36 UTC, Kane610 commented
This is great! I can't promise i can give you feedback within the next.two weeks (busy IRL) but I eagerly want to see this in the integration. Good job!

2024-11-11 13:42 UTC, jonoberheide commented
I may fling some more code over the wall for the Audio Device Control API (for volume control), but no rush on any review!

2024-11-12 02:35 UTC, jonoberheide commented
Added support for the Audio Device Control API. This can control the gain and mute status for output speakers.

https://www.axis.com/vapix-library/subjects/t10100065/section/t10169359/display

The API is a bit kludgy. The GetDevicesSettings returns a huge deeply-nested JSON structure. SetDevicesSetting expects that same structure, even if just tweaking the gain or mute parameters. One approach would be to Get the big structure, modify it, and then Set it, every time you want to change one of those parameters. Another approach, which I took, was to find the minimal JSON fields required for the request to be accepted and Set that. I opened a case with Axis support to see if they have additional guidance.

2024-12-02 17:45 UTC, Kane610 commented
Hey! I should be able to start review this on wednesday

2024-12-09 07:03 UTC, Kane610 requested changes
This is not a complete review, but as it takes a few days between possible times for me right now its better to get it published

2024-12-09 18:08 UTC, jonoberheide commented on axis/interfaces/vapix.py
> +        timeout: int | httpx.Timeout,  # noqa: ASYNC109
ASYNC109 is ruff thinking we're doing timeouts in async code:

https://docs.astral.sh/ruff/rules/async-function-with-timeout/

2024-12-09 18:08 UTC, jonoberheide commented on axis/__main__.py
> +    audio: bool,
Good catch, string!

2024-12-09 18:09 UTC, jonoberheide commented on axis/interfaces/audio_device_control.py
> +        await self._set_gain_mute(mute=True)
Can you clarify? mute should be bool, while gain is int.

2024-12-09 21:10 UTC, Kane610 requested changes

2024-12-09 21:10 UTC, Kane610 commented on axis/models/audio_device_control.py
> +    devices: Any
This should be properly typed

2024-12-09 21:12 UTC, Kane610 commented
Once coming closer to the end remember test coverage is important as well

2024-12-28 17:32 UTC, jonoberheide commented
@Kane610 Sorry for the delay. Unfortunately I think I have to abandon this PR. It turns out the Axis speakers are lacking in capabilities needed for our project. If it's at all helpful, I can ship you one, if you're interested in trying it for testing/maintenance purposes.

2024-12-30 07:46 UTC, Kane610 commented
> @Kane610 Sorry for the delay. Unfortunately I think I have to abandon this PR. It turns out the Axis speakers are lacking in capabilities needed for our project. If it's at all helpful, I can ship you one, if you're interested in trying it for testing/maintenance purposes.

What was it you wanted to achieve that the speaker couldnt manage?

2024-12-30 20:58 UTC, jonoberheide commented
> What was it you wanted to achieve that the speaker couldnt manage?

Limited decoding codec support and audio quality. Also, the Audio Edge Manager API is not sufficient in it's current state (GETs/read-only). Lastly, the behavior of the transmit.cgi endpoint is pretty stateless so makes the HA media player integration not as pleasant (eg. play state, pause, stop, etc).

2025-01-06 09:44 UTC, Kane610 commented
Ill keep it open i might try to complete this

2025-01-06 14:35 UTC, jonoberheide commented
Nice. If you email me your address, I'll ship you a C1410 Mk II. firstname.lastname @ gmail

2025-01-08 19:55 UTC, Kane610 commented
> Nice. If you email me your address, I'll ship you a C1410 Mk II. firstname.lastname @ gmail

That's very kind of you, I already have a C1410 at home

2025-02-25 14:52 UTC, closed without merging