Add authentication support for Companion cameras
Kane610/axis pull request #527
Opened 2024-11-13 15:05 UTC by berlund

Companion cameras require the `Axis-Orig-Sw=true` query string parameter in the rtsp url. Otherwise they respond with a 403.

I do not have the possibility with another camera model, so it's unclear if this affects other cameras. In that case AxisDevice might need some parameter to control this or the info could be derived from Vapix.

2024-11-13 17:41 UTC, Kane610 commented
Hello. This is not a good solution. It should be explicit if its a companion camera or ordinary camera. Some sort of instructions to different paths is needed from a central point

2024-11-13 18:45 UTC, berlund commented
Hi!

Could we do it when creating an AxisDevice, e.g. isCompanion=True ?

/ Lars

> On 13 Nov 2024, at 18:42, Robert Svensson ***@***.***> wrote:
> 
> 
> Hello. This is not a good solution. It should be explicit if its a companion camera or ordinary camera. Some sort of instructions to different paths is needed from a central point
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-11-13 19:52 UTC, Kane610 commented
Adding it to the  config object would be the correct path. And it should default to false

2024-11-15 15:51 UTC, berlund commented
Updated config.

2024-12-02 17:45 UTC, Kane610 commented
Hello! I should be able to start review this on wednesday

2024-12-04 22:00 UTC, Kane610 commented
Your fixing this only for RTSP, can you fix it for vapix as well?

2024-12-12 15:14 UTC, berlund commented
I can fix this, given I find some time these days.

2025-01-31 09:54 UTC, Dempah commented
Hi! I was wondering if and when support for Companion cameras will be added?

2025-02-11 07:46 UTC, berlund reviewed
It's been a while, I have addressed the comments on vapix support

2025-02-22 12:05 UTC, Kane610 requested changes
Ruff fails "Would reformat: axis/stream_manager.py"
And fix that comment, once all tests pass its good to go, good job!

2025-03-23 21:12 UTC, genestealer commented
@berlund Any news on this?

2025-03-25 19:23 UTC, Kane610 approved these changes
Nice!

2025-03-25 19:23 UTC, merged

2026-05-18 13:55 UTC, Dempah commented
Hi. This fix was never implemented, right? Axis Companion cameras still does not work in HA. Works via Frigate though.

2026-05-19 08:17 UTC, berlund commented
> Hi. This fix was never implemented, right? Axis Companion cameras still does not work in HA. Works via Frigate though.

It is implemented here, but I don't know if the HA integration has been updated. Best to check at HA

2026-05-22 22:07 UTC, Kane610 commented
I haven't tested myself, it's supposed to work, but unsure. Just got a companion device but as I don't run windows I can't initialise it yet. Need to play with the api and initialise it that way. Not on my priority list though. Want to help out?

2026-05-25 06:50 UTC, Dempah commented
> I haven't tested myself, it's supposed to work, but unsure. Just got a companion device but as I don't run windows I can't initialise it yet. Need to play with the api and initialise it that way. Not on my priority list though. Want to help out?

Sure! I'm not much of a programmer, but maybe I can help with some testing. I've got four AXIS Companion Dome V, one AXIS Companion Bullet LE and one AXIS M2025-LE. I also have a few Windows and Linux computers along with a Proxmox VE server.

2026-05-26 20:50 UTC, Kane610 commented
Once Copilot tokens reset I will play around with companion support as well. 

You don't need to be much of a programmer, if you trust in the process, have grit and get some support you will grow